# Absolute path to where your maps will go (For CS:GO, /Steam/steamapps/common/Counter-Strike Global Offensive/csgo/maps)
paths:
  CS:S: ""
  CS:GO: ""
  GMod: ""
  
# Token for the discord bot (Don't share this with anyone.)
# You could follow this guide if you don't know how to get a token (https://www.writebots.com/discord-bot-token/)
token: ""

# Whether to check if the mod you are trying to install is supported (1: Enabled, 0: Disabled)
game_check: 1

# Which games to allow downloads for (1: Enabled, 0: Disabled)
# Make sure to put the correct GameBanana game abbreviation if you want to add a custom game
games:
  CS:S: 1
  CS:GO: 0
